name: DAB validate + deploy

on:
  pull_request:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      run_job:
        description: "Run Ingest_Update_MET after deploy?"
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # Databricks auth
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      SPN_DEV: ${{ secrets.SPN_DEV }}
      SPN_PROD: ${{ secrets.SPN_PROD }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate bundle (dev)
        run: databricks bundle validate -t dev

      - name: Bootstrap Unity Catalog (dev)
        run: databricks bundle run bootstrap_uc -t dev

      - name: Deploy bundle (dev)
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: databricks bundle deploy -t dev

      - name: Run job (dev)
        if: github.event_name == 'workflow_dispatch' && inputs.run_job == true
        run: databricks bundle run ingest_update_met -t dev